apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-viewer-binding
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: prod-viewer
    namespace: prod
roleRef:
  kind: Role
  name: prod-viewer
  apiGroup: rbac.authorization.k8s.io
